### ISSUE TITLE
Dataset problems

### ISSUE THREAD

**Issue by phongnhhn92** [mynameisguy/TrafficLightChallenge-DeepLearning-Nexar#1]
I would like to ask would you mind uploading the data you used to the challenge to google drive or something ? I already tried to download from challenge site but it always fails https://challenge.getnexar.com/challenge-1/upload
I hope you can help me :(

**Comment by mynameisguy** [comment]
@phongnhhn92 sorry I can't do that according to their terms.
you need to login with your github account and then you should be able to download it.
if it doesn't work send them an email.
if all doesn't work please reply here and I will try to help
